Repository mdl29/esp-shooter, pull requests merged in 2025-04, with the labels that each got.

#2 1 [Documentation] Add documentation for server and target projects in README.
  README.md
Labels: documentation

#4 3 [Dependency Management] Add python modules requirements file in server project
  server/requirements.txt
Labels: enhancement

#6 5 [Fix] issue in server main code about quotes
  server/main.py
Labels: bug

#8 7 [Dependency Management] Add python modules requirements file in target pio project
  target/target-pio-project/requirements.txt
Labels: enhancement

#13 :bricks: [JumpingTarget] Base FreeCAD part
  target/models/jumping_targets/JumpBase.FCStd
Labels: 3D
